import type { Product } from '@/types/types';

export const products: Product[] = [
    {
        id: '1',
        title: 'CodeCraft IDE',
        description:
            'Professional integrated development environment with advanced code completion and debugging tools.',
        price: '$149.99',
        category: 'Development Tools',
        vendor: 'TechSolutions Inc.',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.8,
        badge: 'Best Seller',
        features: [
            'Multi-language support',
            'Advanced debugging',
            'Git integration',
        ],
    },
    {
        id: '2',
        title: 'DataViz Pro',
        description:
            'Powerful data visualization software that transforms complex data into interactive charts and dashboards.',
        price: '$29.99/mo',
        category: 'Data & Analytics',
        vendor: 'VisualTech',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.5,
        features: [
            'Interactive dashboards',
            'Real-time data',
            'Export options',
        ],
    },
    {
        id: '3',
        title: 'CloudGuard Security Suite',
        description:
            'Comprehensive cloud security solution that protects your applications and data with advanced threat detection.',
        price: '$79.99/yr',
        category: 'Security',
        vendor: 'SecureCloud Systems',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.7,
        badge: 'New',
        features: [
            'Threat detection',
            'Compliance monitoring',
            'Vulnerability scanning',
        ],
    },
    {
        id: '4',
        title: 'ProjectFlow',
        description:
            'Intuitive project management software that helps teams plan, track, and collaborate on projects of any size.',
        price: '$19.99/user',
        category: 'Productivity',
        vendor: 'WorkSmart Solutions',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.3,
        features: ['Task management', 'Team collaboration', 'Gantt charts'],
    },
    {
        id: '5',
        title: 'DesignStudio Pro',
        description:
            'Professional design software for creating stunning graphics, illustrations, and UI/UX designs.',
        price: '$49.99/mo',
        category: 'Design',
        vendor: 'CreativeTech',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.9,
        badge: 'Popular',
        features: ['Vector editing', 'UI/UX tools', 'Asset library'],
    },
    {
        id: '6',
        title: 'ServerMaster',
        description:
            'Advanced server management platform for monitoring, optimizing, and maintaining your server infrastructure.',
        price: '$199.99/yr',
        category: 'DevOps',
        vendor: 'InfraTech Solutions',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.6,
        features: [
            'Performance monitoring',
            'Automated backups',
            'Scaling tools',
        ],
    },
    {
        id: '7',
        title: 'MarketingHub',
        description:
            'All-in-one marketing automation platform that streamlines campaigns and analyzes performance.',
        price: '$39.99/user',
        category: 'Marketing',
        vendor: 'GrowthGenius',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.4,
        features: ['Email campaigns', 'Social media integration', 'Analytics'],
    },
    {
        id: '8',
        title: 'AIAssist',
        description:
            'Intelligent AI assistant that automates repetitive tasks and provides smart suggestions.',
        price: '$24.99/mo',
        category: 'Artificial Intelligence',
        vendor: 'FutureTech AI',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.7,
        badge: 'Trending',
        features: [
            'Task automation',
            'Smart suggestions',
            'Natural language processing',
        ],
    },
    {
        id: '9',
        title: 'DatabasePro',
        description:
            'Robust database management system with advanced querying and optimization tools.',
        price: '$59.99/yr',
        category: 'Development Tools',
        vendor: 'DataSystems Inc.',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.5,
        features: ['Query optimization', 'Data modeling', 'Backup & recovery'],
    },
    {
        id: '10',
        title: 'CloudStorage Enterprise',
        description:
            'Secure and scalable cloud storage solution for businesses with advanced file management.',
        price: '$15.99/TB',
        category: 'Cloud Services',
        vendor: 'CloudWorks',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.2,
        features: [
            'Unlimited storage',
            'Advanced security',
            'Team collaboration',
        ],
    },
    {
        id: '11',
        title: 'CRM Advantage',
        description:
            'Comprehensive customer relationship management software for managing contacts and sales.',
        price: '$35.99/user',
        category: 'Business',
        vendor: 'SalesForce Solutions',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.6,
        features: ['Contact management', 'Sales pipeline', 'Customer support'],
    },
    {
        id: '12',
        title: 'VideoEdit Master',
        description:
            'Professional video editing software with advanced effects and transitions for creating stunning content.',
        price: '$69.99/mo',
        category: 'Media',
        vendor: 'MediaPro Studios',
        image: '/placeholder.svg?height=300&width=400',
        rating: 4.8,
        badge: "Editor's Choice",
        features: ['4K editing', 'Special effects', 'Audio enhancement'],
    },
];
