#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Running linters
npm run lint && npm run format||
(
    echo '😤 Something went wrong! 😤'
    false;
)

# All checks are passed
echo '✅ All checks are passed. Committing... ✅'
